using Godot;
using MagicSwordsman.MagicSwordsmanCode.Cards;
using MagicSwordsman.MagicSwordsmanCode.Combat;
using MagicSwordsman.MagicSwordsmanCode.Swords;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Models;

namespace MagicSwordsman.MagicSwordsmanCode.Visuals;

/// <summary>
/// Presentation only: picks which of the combat scene's clips (tools/motion_list.txt, generated by
/// tools/gen_combat_scene.py) Ensifer plays. The game itself only fires "Attack" (attack commands), "Hit" and
/// "Dead"; our cards never fire "Cast". So:
///  - "Attack" / "Hit" / "Dead" started by the game are swapped for a variant (<see cref="Redirect"/>);
///  - skills and powers play a Cast_* / Power_* clip when the card is played (<see cref="OnCardPlayed"/>);
///  - block, damage, summons, sword switches, turn start, victory and idle fidgets come from our own hooks.
/// Every entry point swallows its errors; a missing clip just leaves the current one playing.
/// </summary>
public static class MotionDirector
{
    private static readonly string[] Attacks =
        ["Attack", "Attack_Thrust", "Attack_Backhand", "Attack_Sweep", "Attack_Left", "Attack_Command"];
    private static readonly string[] HeavyAttacks = ["Attack_Heavy", "Attack_Overhead"];
    private static readonly string[] Casts = ["Cast", "Cast_Point", "Cast_LeftHand", "Cast_Chest", "Cast_Wide", "Cast_Draw"];
    private static readonly string[] TargetedCasts = ["Cast_Point", "Cast_Debuff"];
    private static readonly string[] Powers = ["Power_Rise", "Power_Focus", "Power_Burst"];
    private static readonly string[] Blocks = ["Block", "Block_Cross", "Block_Brace", "Block_Palm"];
    private static readonly string[] Swaps = ["Swap_1", "Swap_2", "Swap_3"];
    private static readonly string[] Fidgets = ["Idle_Look", "Idle_Flex", "Idle_Weave", "Idle_Breath"];
    private static readonly string[] Deaths = ["Dead", "Dead_Kneel"];

    private static readonly Random Rng = new();

    /// <summary>Last card this player played (to pick the attack variant when the game fires "Attack").</summary>
    private static readonly Dictionary<ulong, CardModel> LastCard = new();

    /// <summary>Target of the last card played (where the sword flies when the game fires "Attack").</summary>
    private static readonly Dictionary<ulong, Creature?> LastTarget = new();

    private const string HookMeta = "ms_motion_hook";

    // ------------------------------------------------------------------ hooks called by Mangeomchong / SwordCombat

    public static void OnCardPlayed(Player player, CardPlay play)
    {
        try
        {
            LastCard[player.NetId] = play.Card;
            LastTarget[player.NetId] = play.Target;
            switch (play.Card.Type)
            {
                case CardType.Power:
                    Play(player, Pick(Powers));
                    break;
                case CardType.Skill:
                    var targeted = play.Card.TargetType is TargetType.AnyEnemy or TargetType.AllEnemies
                        or TargetType.RandomEnemy;
                    Play(player, Pick(targeted ? TargetedCasts : Casts));
                    break;
            }
        }
        catch (Exception e)
        {
            MainFile.Logger.Warn($"[MotionDirector] card motion failed: {e.Message}");
        }
    }

    public static void OnBlockGained(Player player, decimal amount) =>
        Play(player, amount >= 15 ? "Block_Big" : Pick(Blocks));

    public static void OnDamageReceived(Player player, int unblocked, bool fullyBlocked)
    {
        var creature = player.Creature;
        if (creature.IsDead) return;
        if (fullyBlocked) { Play(player, "Hit_Guarded"); return; }
        if (unblocked <= 0) return;
        var heavy = unblocked >= Math.Max(15, creature.MaxHp / 5);
        Play(player, heavy ? "Hit_Heavy" : unblocked >= 8 ? "Hit_Stagger" : unblocked <= 3 ? "Hit_Light" : "Hit");
    }

    public static void OnSummoned(Player player, SwordId sword) => Play(player, "Summon_" + sword);

    /// <summary>A switch usually happens inside a card play: only gesture if nothing else is playing.</summary>
    public static void OnSwitched(Player player) => Play(player, Pick(Swaps), onlyIfIdle: true);

    public static void OnTurnStart(Player player) => Play(player, "TurnStart", onlyIfIdle: true);

    public static void OnVictory(Player player) => Play(player, "Victory");

    // ------------------------------------------------------------------ AnimationPlayer wiring

    /// <summary>
    /// Called once per combat rig (SwordVisuals): swaps the game's generic triggers for variants, returns to idle
    /// after one-shot clips and plays an idle fidget now and then.
    /// </summary>
    internal static void Hook(Player player, AnimationPlayer anim)
    {
        if (anim.HasMeta(HookMeta) || !anim.HasAnimation("idle")) return;
        anim.SetMeta(HookMeta, true);
        // every switch between clips is cross-faded a little (it used to snap, e.g. when an idle fidget started mid
        // breath — bug report 2026-10-09); idle <-> fidget gets a longer, invisible blend below
        anim.PlaybackDefaultBlendTime = 0.15;

        anim.AnimationStarted += name =>
        {
            var variant = Redirect(player, name);
            if (variant == null || variant == name || !anim.HasAnimation(variant)) return;
            // not from inside the signal: let the started clip settle first (one frame of it is invisible)
            Callable.From(() =>
            {
                if (GodotObject.IsInstanceValid(anim) && anim.CurrentAnimation == name) anim.Play(variant);
            }).CallDeferred();
        };

        anim.AnimationFinished += name =>
        {
            if (!GodotObject.IsInstanceValid(anim) || name.ToString().StartsWith("Dead")) return;
            if (name != "idle") anim.Play("idle", name.ToString().StartsWith("Idle_") ? 0.6 : 0.25);
        };

        var timer = new Godot.Timer { WaitTime = 6.5, Autostart = true, Name = "MotionFidget" };
        timer.Timeout += () =>
        {
            timer.WaitTime = 5.5 + Rng.NextDouble() * 5;
            if (!GodotObject.IsInstanceValid(anim) || anim.CurrentAnimation != "idle") return;
            var fidget = Pick(Fidgets);
            if (anim.HasAnimation(fidget)) anim.Play(fidget, 0.6);
        };
        anim.AddChild(timer);
    }

    private static string? Redirect(Player player, StringName started)
    {
        try
        {
            switch (started.ToString())
            {
                case "Attack":
                    LastTarget.TryGetValue(player.NetId, out var target);
                    SwordVisuals.Strike(player, target);
                    return AttackVariant(player);
                case "Dead":
                    return Pick(Deaths);
                default:
                    return null;
            }
        }
        catch (Exception e)
        {
            MainFile.Logger.Warn($"[MotionDirector] redirect failed: {e.Message}");
            return null;
        }
    }

    private static string AttackVariant(Player player)
    {
        LastCard.TryGetValue(player.NetId, out var card);
        // a sword's own cards fight in that sword's style; other attacks use the generic library
        var sword = (card as MagicSwordCard)?.Sword ?? SwordCombat.CurrentSword(player);
        if (sword is { } s && Rng.NextDouble() < (card is MagicSwordCard ? 0.75 : 0.4)) return "Attack_" + s;
        if (card != null && card.EnergyCost.GetResolved() >= 2) return Pick(HeavyAttacks);
        if (card?.TargetType == TargetType.AllEnemies) return "Attack_Sweep";
        var roll = Rng.NextDouble();
        return roll < 0.12 ? "Attack_Double" : roll < 0.2 ? "Attack_Flurry" : Pick(Attacks);
    }

    // ------------------------------------------------------------------ helpers

    private static string Pick(string[] options) => options[Rng.Next(options.Length)];

    private static void Play(Player player, string clip, bool onlyIfIdle = false) =>
        SwordVisuals.PlayMotion(player, clip, onlyIfIdle);

    /// <summary>Combat over: forget per-combat state.</summary>
    public static void Clear(Player player)
    {
        LastCard.Remove(player.NetId);
        LastTarget.Remove(player.NetId);
    }

    /// <summary>Our hit landed on an enemy (later hits of multi-hit / random-target attacks): the sword flies there.</summary>
    public static void OnDealtDamage(Player player, Creature target) => SwordVisuals.Strike(player, target);
}
